### ISSUE TITLE
a simple text file can not upload properly

### ISSUE THREAD

**Issue by mahaidong** [mesuutt/python-chunked-upload-example#1]
I try to upload a very simple txt file like this:

```
111111111111111111111111111
22222222222222222222
33333333333333333333
```

and set the config.py  as   `MAX_UPLOAD_BYTE_LENGHT = 4  # 4byte`

it not work well.

**Comment by mesuutt** [comment]
@mahaidong thanks you for finding the bug. I solved it :+1:  look at f177be0e9 and a6826fbf

**Comment by mahaidong** [comment]
cool , I will debug it 

> @mahaidong thanks you for finding the bug. I solved it 👍 look at [f177be0](https://github.com/mesuutt/python-chunked-upload-example/commit/f177be0e93f32327c94a74ffcb07d5773e067213) and [a6826fb](https://github.com/mesuutt/python-chunked-upload-example/commit/a6826fbf76d81607e7e5aeacd86329bdd3490308)

**Comment by mahaidong** [comment]
Firstly , thanks for your work and fast reply.
I test a txt file , it pass
I test a png file, it pass
I test a pdf file , it fail. this is the pdf file i   got https://smallpdf.com/blog/sample-pdf

**Comment by mesuutt** [comment]
@mahaidong I tested it by set `MAX_UPLOAD_BYTE_LENGHT` to `4`, `1` and it works correct. 
I tested it with md5sum and open pdf in browser.
Did you sure pulled last changes from repo. 
Which operation system did you run with? Maybe platform specific bug. I am running it on Linux.

**Comment by mahaidong** [comment]
> @mahaidong I tested it by set `MAX_UPLOAD_BYTE_LENGHT` to `4`, `1` and it works correct.
> I tested it with md5sum and open pdf in browser.
> Did you sure pulled last changes from repo.
> Which operation system did you run with? Maybe platform specific bug. I am running it on Linux.

cool , I test on Mac and Ubnutu , it works for single page pdf  from https://smallpdf.com/blog/sample-pdf .

Then I start to test this one  https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf

it not working.

**Comment by mesuutt** [comment]
@mahaidong I tested with given pdf file and it uploaded fine without any problem :thinking: 
I am making validation with md5sum.

**Comment by mahaidong** [comment]
> @mahaidong I tested with given pdf file and it uploaded fine without any problem thinking
> I am making validation with md5sum.

not working for me  :( 

in Ubuntu 18 python2.7.17   after uploaded , I can not open this pdf file.

the following is the screen shoot:  

https://github.com/mahaidong/issues/blob/master/Screenshot%20from%202020-03-15%2016-19-21.png

https://github.com/mahaidong/issues/blob/master/Screenshot%20from%202020-03-15%2016-25-56.png

**Comment by mesuutt** [comment]
Can you try with python3 and check md5sum of files?

**Comment by mahaidong** [comment]
I will try it

**Comment by mahaidong** [comment]
> Can you try with python3 and check md5sum of files?

it works in python3

**Comment by mesuutt** [comment]
@mahaidong I will find and solve python2 related bug when I have free time. Thanks

**Comment by mesuutt** [comment]
@ I solved the problem and updated the code. :+1:

**Comment by mahaidong** [comment]
> @ I solved the problem and updated the code. +1

cool! I test on python2 , it works
